### ISSUE TITLE
anchoring bug

### ISSUE THREAD

**Issue by sa-lee** [sa-lee/plyranges#28]
From https://github.com/Bioconductor/Contributions/issues/670

The anchoring mechanism only works properly on IRanges and GRanges instances. When used on an IRanges or GRanges derivative, it returns an IRanges or GRanges instance which is not what one would expect. For example, with a VRanges object (derives from GRanges):

> library(VariantAnnotation)
> example(VRanges)
> set_width(anchor_start(vr), 20)
GRanges object with 2 ranges and 1 metadata column:
      seqnames    ranges strand | tumorSpecific
         <Rle> <IRanges>  <Rle> |     <logical>
  [1]     chr1      1-20      * |         FALSE
  [2]     chr2     10-29      * |          TRUE
  -------
  seqinfo: 2 sequences from an unspecified genome; no seqlengths

**Comment by sa-lee** [comment]
This also affects grouping
```{r}
> group_by(vr, strand)
GRanges object with 2 ranges and 1 metadata column:
Groups: strand
      seqnames    ranges strand | tumorSpecific
         <Rle> <IRanges>  <Rle> |     <logical>
  [1]     chr1  [ 1,  5]      * |         FALSE
  [2]     chr2  [10, 20]      * |          TRUE
  -------
  seqinfo: 2 sequences from an unspecified genome; no seqlengths
```
@lawremi to get these features on derivative Ranges classes I'm guessing I need to make a virtual class for them?

**Comment by lawremi** [comment]
The problem is illustrated by the C++ example [here](https://en.wikipedia.org/wiki/Decorator_pattern). We want what they call a static decorator, where we add the annotation to every subclass of GenomicRanges. For example, we could have GRangesAnchored contain GenomicRanges instead of GRanges, but what happens when we get a VRanges? The "V" aspect is lost. S4 does not support mixins or templates, so we will have to compromise somehow. Some choices:

- We could just identify all the important GenomicRanges derivatives and decorate each one using multiple inheritance, kind of like the Java example on the wikipedia page, except we need to use multiple inheritance instead of interfaces.
- The class system _is_ dynamic, so in theory we could create new classes on the fly, overriding the methods from the mixin (so VRangesAnchored would be created on the fly). The details would be tricky though.
- We could do something at the instance level. Simplest would be to use the metadata slot, even though that is reserved for user use. We could create some hidden metadata fields, prefixed with ".".  In practice this will probably work, but it is abusing the metadata slot, and we won't be able to use dispatch.

**Comment by sa-lee** [comment]
How about this?

I was thinking of refactoring the classes to use the DelegatingGenomicRanges class in GenomicRanges - not sure if there's equivalent for IRanges but guess I could create one.

So my new class looks like this
```{r}
setClass("GRangesAnchored",
         representation =   representation(anchor = "character"),
         contains = c("GRanges", "DelegatingGenomicRanges"))
```

Then the constructor for an anchored class place the input ranges object into the delegate slot. 

Then set_width/stretch dispatches on the delegating ranges and modifies it and then returns the delegate. 

I think using that approach any structure in the derivative ranges object will be maintained. 
But I guess we will also need to update methods for our other generics. 

What do you think?

**Comment by sa-lee** [comment]
Just realized that using DelegatingGenomicRanges could greatly simplify the deferred reader logic too 😃

**Comment by lawremi** [comment]
The structure will be maintained, but the object will be a GRanges, not e.g. a VRanges, so the VRanges functionality is hidden by the decoration. It's better to contain GenomicRanges instead of GRanges, since there is no need for the GRanges implementation when we are delegating.

**Comment by sa-lee** [comment]
Re your point about dynamic class system does that mean something like this is possible:

```
setClass("GenomicRangesAnchored",
         representation = representation(anchor = "character"),
         contains = c("VIRTUAL", "DelegatingGenomicRanges"),
         validity = validGRangesAnchored)


new_anchored <- function(rng, anchor) {
  cls <- class(rng)
  new_cls <- paste0(cls, "Anchored")
  setClass(new_cls, contains = c(cls, "GenomicRangesAnchored"))
  new(new_cls, rng, delegate = rng, anchor = anchor)
}
```

So the VRangesAnchored could be done on the fly?

**Comment by lawremi** [comment]
Yes, that is what I meant. The trickiest part would be setting the delegating methods automatically. It would need methods that defer to the mixin class (e.g. "Anchored") and methods that just delegate.

To clarify my last post, there is no need for GRangesAnchored (or AnchoredGenomicRanges might be better name?) to inherit from GRanges. Containing DelegatingGenomicRanges is enough.

**Comment by sa-lee** [comment]
@lawremi when you do this dynamic class system - how do you avoid namespace conflicts?
I keep getting an error:
Error in assign(mname, def, where) : 
  cannot add bindings to a locked environment

**Comment by sa-lee** [comment]
Ok I've used the `where` argument  in `setClass` to get around this. 
For the mixin - could we dynamically create any methods that dispatch on the input class to dispatch on the anchored class.

**Comment by sa-lee** [comment]
this is partially completed aside from refactoring `group_by` 
I suppose I need to add methods for `DelegatingGenomicRanges` for all the verbs too.

**Comment by lawremi** [comment]
If you do manage to pull off a general mixin mechanism for S4, you should split it off into a separate package and maybe scribble down an R Journal article on it.

**Comment by lawremi** [comment]
I've thought more about this, and I think is going to be really tricky to get right. I think we should just instantiate AnchoredGenomicRanges, without defining any new classes or trying to emulate mixins.

The problem with semantically enriching classes like VRanges may not be such a big deal, because we are in general limiting special methods anyway. For example, it is not a big deal that we can't call `alt(delegator)` to get the ALT allele from the underlying VRanges, because stuff like `overscope_ranges()` is just going to work (e.g. by delegation to `as.env()`). So let's just keep it simple.

Agreed?

**Comment by sa-lee** [comment]
I agree - thinking about the workflows for these things I don't think a user would have an anchored range stick around for very long (the whole reason to anchor is to then pass the ranges to set_width or stretch) so I think just making sure it's simple and works is fine.
