### ISSUE TITLE
Implement dplyr methods for DataFrame

### ISSUE THREAD

**Issue by jonocarroll** [sa-lee/plyranges#57]
Some reading:

 - https://stat.ethz.ch/pipermail/bioc-devel/2015-April/007417.html
 - https://github.com/tidyverse/tibble/issues/108 (though support for more complex objects such as `AnnotatedDataFrame` would be more complex)

One generalised approach: https://gist.github.com/mjsteinbaugh/952e2263650262da1a93a560b0a98ccc

This appears to work okay, but returns a `data.frame`. Trivial to return `DataFrame` instead.

Pingback with draft for mutate as an S4 method: https://github.com/sa-lee/plyexperiment/pull/4

By converting to `tbl_df` rather than `data.frame` list-columns can be preserved properly but @mjsteinbaugh's solution seems to handle them just fine.

The big question is should this be done in `plyranges` or its own package (which `playranges` can import)?

**Comment by sa-lee** [comment]
I think this should be its own package. The current approach in plyranges is to use  masks + rlang to avoid doing things like `as.data.frame()`, that way weird and wonderful S4 classes (like GRangesList or S4List  or Rles or nested DataFrame columns) are preserved.  See https://github.com/sa-lee/plyranges/blob/master/R/ranges-eval.R

**Comment by mjsteinbaugh** [comment]
@jonocarroll Take a look at my [transformer](https://github.com/steinbaugh/transformer) package. It adds S3 and S4 method support for interconversion between `DataFrame` and `tbl_df`. I tweaked the default row name handling for `as_tibble()` so that it doesn't drop row names when coercing from a `DataFrame`. Then at the end of your dplyr chain you can easily coerce back to `DataFrame` simply using `as()`.

**Comment by jonocarroll** [comment]
As a proper backend? https://krlmlr.github.io/fstplyr/articles/implement.html

**Comment by sa-lee** [comment]
Closing this now, as DFplyr is a thing.
